<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation email' => 'Email de ativação',
    'This email has already been taken.' => 'Este e-mail já está sendo usado',
    'Your account has been successfully activated.' => 'Conta ativada corretamente',
    'Your account has been successfully created. Check your email for further instructions.' => 'Conta criada corretamente. Verifique as instruções no seu e-mail',
    'Your activation link: {url}' => 'Link de ativação: {url}',
    'About' => 'Sobre',
    'Account Settings' => 'Configuração da Conta',
    'Articles' => 'Artigos',
    'Attachments' => 'Anexos',
    'Backend' => 'Backend',
    'Body' => 'Corpo',
    'Check your email for further instructions.' => 'Verifique as instruções no seu e-mail.',
    'Confirm Password' => 'Confirmar senha',
    'Contact' => 'Contato',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Erro no proceso de OAuth.',
    'Female' => 'Feminino',
    'Home' => 'Inicio',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Redefinir senha <a href="{link}">aqui</a>',
    'Incorrect username or password.' => 'Usuário ou senha incorretos',
    'Language' => 'Idioma',
    'Log in with' => 'Entrar com',
    'Login' => 'Entrar',
    'Logout' => 'Sair',
    'Male' => 'Masculino',
    'Name' => 'Nome',
    'Need an account? Sign up.' => 'Precisa de uma conta? Registre-se',
    'New password was saved.' => 'Nova senha gravada',
    'Page not found' => 'Página não encontrada',
    'Password' => 'Senha',
    'Password reset for {name}' => 'Redefinir senha para {name}',
    'Profile settings' => 'Configurações de perfil',
    'Remember Me' => 'Lembrar-me',
    'Request password reset' => 'Solicitar redefinição de senha',
    'Reset password' => 'Redefinir Senha',
    'Settings' => 'Configurações',
    'Sign up with' => 'Registrar com',
    'Signup' => 'Registrar',
    'Sorry, we are unable to reset password for email provided.' => 'Não foi possível redefinir a senha para o email informado',
    'Subject' => 'Assunto',
    'Submit' => 'Enviar',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Obrigado por entrar em contato. Responderemos assim que possível',
    'There was an error sending email.' => 'Erro ao enviar email',
    'This email address has already been taken.' => 'Endereço de email já utilizado',
    'This username has already been taken.' => 'Usuário já está sendo usado',
    'Update' => 'Atualizar',
    'User Settings' => 'Configurações de usuario',
    'Username' => 'Usuário',
    'Username or email' => 'Usuário ou email',
    'Verification Code' => 'Código de verificação',
    'We already have a user with email {email}' => 'Já xiste um usuário com o email {email} ',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Bem-vindo {app-name}!. Uma mensagem com informações de login foi enviada para seu e-mail',
    'Your account has been successfully saved' => 'Conta gravada com sucesso!',
    '{app-name} | Your login information' => '{app-name} | Informações',
];
