#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(dirname(__DIR__) . '/../../vendor/autoload.php');
require(dirname(__DIR__) . '/../../vendor/yiisoft/yii2/Yii.php');

// Bootstrap application
require(__DIR__ . '/../bootstrap.php');
require(__DIR__ . '/../bootstrap-local.php');

$config = \yii\helpers\ArrayHelper::merge(
    // Common
    require(__DIR__ . '/../../../common/config/base.php'),
    require(__DIR__ . '/../../../common/config/console.php'),
    require(__DIR__ . '/../../../console/config/console.php'),
    // Environment specific
    require(__DIR__ . '/../common/config/base.php'),
    require(__DIR__ . '/../common/config/base-local.php'),
    require(__DIR__ . '/../common/config/console.php'),
    require(__DIR__ . '/../common/config/console-local.php'),
    require(__DIR__ . '/config/console.php'),
    require(__DIR__ . '/config/console-local.php')
);


$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
