#!/usr/bin/env php
<?php
// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

// Composer
require(__DIR__ . '/../vendor/autoload.php');

// Environment
require(__DIR__ . '/../common/Environment.php');
$environment = new Environment([
    //'envVar'=>'YII_ENV',
    //'env'=>null,
    //'debugVar'=>'YII_DEBUG',
    //'debug'=>null,
]);

// Yii
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

// Bootstrap application
require(__DIR__ . '/../common/config/bootstrap.php');

$config = \yii\helpers\ArrayHelper::merge(
// Common
    require(__DIR__ . '/../common/config/base.php'),
    require(__DIR__ . '/../common/config/base-local.php'),
    require(__DIR__ . '/../common/config/console.php'),
    require(__DIR__ . '/../common/config/console-local.php'),
    require(__DIR__ . '/config/console.php'),
    require(__DIR__ . '/config/console-local.php')
);

$exitCode = (new yii\console\Application($config))->run();
exit($exitCode);
