x-yii: &yii
  image: yiisoftware/yii2-php:8.2-fpm
  environment:
    - PHP_ENABLE_XDEBUG=1
    - XDEBUG_MODE=develop,debug
  working_dir: /app
  volumes:
    - ./:/app
    - ./docker/php/php.ini:/usr/local/etc/php.ini
    - ./docker/php/www.conf:/usr/local/etc/www.conf
  depends_on:
    mariadb:
      condition: service_healthy
  restart: "unless-stopped"

services:
  frontend:
    <<: *yii

  backend:
    <<: *yii

  console:
    <<: *yii

  storage:
    <<: *yii

  api:
    <<: *yii

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - api
      - frontend
      - backend
      - console
      - storage

  node:
    image: node:24-alpine
    volumes:
      - ./:/app
    working_dir: /app

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"

  mariadb:
    image: mariadb:11.8
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${DB_MAIN}
      MYSQL_USER:          ${DB_USERNAME}
      MYSQL_PASSWORD:      ${DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  adminer:
    build:
      context: ./docker/adminer
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_PLUGINS: "backward-keys config dump-alter dump-date dump-json dump-php dump-zip edit-foreign enum-option json-column pretty-json-column table-indexes-structure table-structure AdminerForeignKeysPlugin AdminerShowColumnComment display-foreign-key-name FasterTablesFilter"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  default:
    name: yii2-starter-kit_default