<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{attribute}" must be a valid JSON' => '"{attribute}" JSON formátúnak kell lennie',
    'API access token' => '',
    'Active' => 'Aktív',
    'Article ID' => 'Cikk azonosító',
    'Article View' => '',
    'Author' => 'Szerző',
    'Base URL' => '',
    'Base Url' => '',
    'Body' => 'Szövegtörzs',
    'Caption' => 'Felítart',
    'Carousel ID' => 'Körhinta azon',
    'Category' => 'Kategória',
    'Comment' => 'Megjegyzés',
    'Component' => 'Kompnens',
    'Config' => 'Konfig',
    'Created At' => 'Létrehozás',
    'Created at' => 'Létrehozás',
    'Deleted' => 'Törölve',
    'Down to maintenance.' => 'Karbantartás módba',
    'Draft' => 'Vázlat',
    'E-mail' => '',
    'Email' => '',
    'Expire At' => 'Lejár',
    'File Type' => 'Fájltípus',
    'Firstname' => 'Keresztnév',
    'Gender' => 'Neme',
    'ID' => 'Azon.',
    'Image' => 'Kép',
    'Key' => 'Kulcs',
    'Last login' => 'Utolsó belépés',
    'Lastname' => 'Családnév',
    'Locale' => 'Nyelv',
    'Middlename' => 'Középsőnév',
    'Name' => 'Név',
    'Not Active' => 'Nem aktív',
    'Order' => 'Rendezés',
    'Page View' => 'Kép nézet',
    'Parent Category' => 'Szülő kategória',
    'Password' => 'Jelszó',
    'Path' => '',
    'Picture' => 'Kép',
    'Published' => 'Megjelenítve',
    'Published At' => 'Megjelenés ideje',
    'Roles' => 'Jogosultság',
    'Size' => 'Méret',
    'Slug' => '',
    'Status' => 'Státusz',
    'Thumbnail' => 'Bélyegkép',
    'Title' => 'Cím',
    'Token' => '',
    'Type' => 'Típus',
    'Updated At' => 'Módosítva',
    'Updated at' => 'Módosítva',
    'Updater' => 'Módosító',
    'Upload Ip' => 'Feltöltés IP',
    'Url' => '',
    'User ID' => 'Felhasználó azon.',
    'Username' => 'Felhasználó',
    'Value' => 'Érték',
];
