<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Magunkról',
    'Account Settings' => 'Felhasználói beállítások',
    'Activation email' => 'Aktiváló email',
    'Archive' => 'Acrhívált',
    'Articles' => 'Cikkek',
    'Attachments' => 'Csatolmányok',
    'Backend' => 'Admin',
    'Body' => 'Szöveg',
    'Categories' => 'Kategóriák',
    'Categories not found' => 'Kategória nem található',
    'Change Password' => 'Jelszó módosítása',
    'Check your email for further instructions.' => 'Ellenörzid az emailjeid további utasításért!',
    'Confirm Password' => 'Jelszó megerősítése',
    'Contact' => 'Kapcsolat',
    'Contact Support' => 'Support kapcsolat',
    'Contact us' => 'Kapcsolat',
    'Create Rule' => 'Jog létrehozás',
    'E-mail' => '',
    'Email' => '',
    'Error while oauth process.' => 'Hiba ouath közben',
    'Female' => 'Nő',
    'Forgot your password?' => 'Elfeljtett jelszó',
    'Go to Home' => 'Cimoldara',
    'Home' => 'Címoldal',
    'Incorrect username or password.' => 'Hibás felhasználónév vagy jelszó',
    'Language' => 'Nyelv',
    'Last updated on {updated_at} by {updater}' => 'Utolsó módosítás {updated_at} {updater}',
    'Log in with' => 'Belépés mint',
    'Login' => 'Belépés',
    'Logout' => 'Kilépés',
    'Male' => 'Férfi',
    'Name' => 'Név',
    'Need an account? Sign up.' => 'Felhasználó létrehozáshoz, lépjen be!',
    'New password was saved.' => 'Új jelszó mentve',
    'No records' => 'Nincs rekord',
    'Oops! There was an error...' => 'Hiba törént.. :(',
    'Page not found' => 'Oldal nem található',
    'Password' => 'Jelszó',
    'Password reset for {name}' => 'Jelszó visszaállítás {name} részére',
    'Posted by {author} on {published_at}' => 'Beküldve {author} {published_at}',
    'Profile settings' => 'Profil beállítás',
    'Read More ' => 'Tovább',
    'Remember Me' => 'Emlékezz rám',
    'Request password reset' => 'Új jelszó kérése',
    'Resend activation email' => 'Aktiváló email újra küldése',
    'Resend my activation email' => 'Aktiváló email újra küldése',
    'Reset password' => 'Jelszó visszaállítás',
    'Rules' => 'Jogok',
    'Send Email' => 'Email küldés',
    'Settings' => 'Beállítás',
    'Sign up' => 'Belépés',
    'Sign up with' => 'Belépés mint',
    'Signup' => 'Belépés',
    'Sorry, we are unable to resend activation link for email provided.' => 'Elnézést, a megadott email címre nem tudunk aktíváló mail-t küldeni!',
    'Sorry, we are unable to reset password for email provided.' => 'Elnézést, a megadott email címre nem tudunk jelszó újra generáló email-t küldeni!',
    'Subject' => 'Tárgy',
    'Submit' => 'Mentés',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Köszönjük üzenetét! Hamarosan megkeresük Önt!',
    'There was an error sending email.' => 'Hiba történt email küldés közben',
    'This email address has already been taken.' => 'Email már foglalt',
    'This email has already been taken.' => 'Email már foglalt',
    'This username has already been taken.' => 'Felhasználónév már foglalt',
    'Update' => 'Módosítás',
    'User Settings' => 'Felhasználó beállítások',
    'Username' => 'Felhasználó',
    'Username or email' => 'Felhasználónév vagy jelszó',
    'Verification Code' => 'Ellenőrző kód',
    'We already have a user with email {email}' => 'Már létezik felhasználó ezzel az email címmel {email}',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Üdvözöljük {app-name}-on. Belépéshez szükséges információk emialben elküldtük!',
    'Your account has been successfully activated.' => 'Felhasználói regisztrációja sikeresen aktíválva!',
    'Your account has been successfully created. Check your email for further instructions.' => 'Felhasználója sikeresen létrejött. Ellenőrizze emailjeit tovább lépéshez!',
    'Your account has been successfully saved' => 'Felhasználója sikeresen mentve!',
    'Your activation link: {url}' => 'Aktiváló link: {url}',
    'by {author} on {published_at} in {category}' => 'szerző {author} {published_at} {category}',
    '{app-name} | Your login information' => '{app-name} | Belépés információk',
];
