<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'Activation email' => 'Email d\'activation',
'This email has already been taken.' => 'Cet email a déjà été pris.',
'Your account has been successfully activated.' => 'Votre compte a été activé avec succès.',
'Your account has been successfully created. Check your email for further instructions.' => 'Votre compte à été créé avec succès. Vérifiez votre email pour plus d\'instructions.',
'Your activation link: {url}' => 'Votre lien d\'activation: {url}',
'About' => 'A notre sujet',
'Account Settings' => 'Paramètres du compte',
'Articles' => 'Articles',
'Attachments' => 'Pièces jointes',
'Backend' => 'Backend',
'Body' => 'Corps',
'Check your email for further instructions.' => 'Vérifiez votre email pour plus d\'instructions.',
'Confirm Password' => 'Confirmez le mot de passe',
'Contact' => 'Contact',
'E-mail' => 'Email',
'Email' => 'Email',
'Error while oauth process.' => 'Erreur lors du processus oauth.',
'Female' => 'Féminin',
'Home' => 'Accueil',
'If you forgot your password you can reset it &lt;a href=&quot;{link}&quot;&gt;here&lt;/a&gt;' => 'Si vous avez oublié votre mot de passe, vous pouvez le réinitialiser & lt; a href = & quot; {link} & quot; & gt; here & lt; / a & gt;',
'Incorrect username or password.' => 'Identifiant ou mot de passe incorrect.',
'Language' => 'La langue',
'Log in with' => 'Connectez-vous avec',
'Login' => 'S\'identifier',
'Logout' => 'Sortir',
'Male' => 'Mâle',
'Name' => 'prénom',
'Need an account? Sign up.' => 'Besoin d\'un compte? S\'inscrire.',
'New password was saved.' => 'Le nouveau mot de passe a été enregistré.',
'Page not found' => 'Page non trouvée',
'Password' => 'Mot de passe',
'Password reset for {name}' => 'Réinitialisation du mot de passe pour {name}',
'Profile settings' => 'Paramètres de profil',
'Remember Me' => 'Souviens-toi de moi',
'Request password reset' => 'Demander la réinitialisation du mot de passe',
'Reset password' => 'Réinitialiser le mot de passe',
'Settings' => 'Réglages',
'Sign up with' => 'Se connecter avec',
'Signup' => 'S\'inscrire',
'Sorry, we are unable to reset password for email provided.' => 'Désolé, nous ne pouvons pas réinitialiser le mot de passe pour cet email.',
'Subject' => 'Sujet',
'Submit' => 'Soumettre',
'Thank you for contacting us. We will respond to you as soon as possible.' => 'Merci de nous contacter. Nous vous répondrons dans les meilleurs délais.',
'There was an error sending email.' => 'Une erreur s\'est produite lors de l\'envoi du courrier électronique.',
'This email address has already been taken.' => 'Cette adresse e-mail a déjà été prise.',
'This username has already been taken.' => 'Ce nom d\'utilisateur a déjà été pris.',
'Update' => 'Mettre à jour',
'User Settings' => 'Paramètres utilisateur',
'Username' => 'Nom d\'utilisateur',
'Username or email' => 'Nom d\'utilisateur ou email',
'Verification Code' => 'Code de vérification',
'We already have a user with email {email}' => 'Nous avons déjà un utilisateur avec email {email}',
'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Bienvenue sur {app-name}. Un email contenant vos informations de connexion a été envoyé à votre adresse email.',
'Your account has been successfully saved' => 'Votre compte a été enregistré avec succès',
'{app-name} | Your login information' => '{app-name} | Vos informations de connexion',
];
