<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Tentang',
    'Account Settings' => 'Pengaturan Akun',
    'Activation email' => 'Aktivasi Surel',
    'Articles' => 'Artikel',
    'Attachments' => 'Lampiran',
    'Backend' => 'Backend',
    'Body' => 'Badan',
    'Check your email for further instructions.' => 'Cek surel untuk instruksi berikutnya.',
    'Confirm Password' => 'Konfirmasi Password',
    'Contact' => 'Kontak',
    'E-mail' => 'Surel',
    'Email' => 'Surel',
    'Error while oauth process.' => 'Rusak ketika proses oauth.',
    'Female' => 'Wanita',
    'Home' => 'Beranda',
    'Incorrect username or password.' => 'Username atau password salah.',
    'Language' => 'Bahasa',
    'Log in with' => 'Masuk dengan',
    'Login' => 'Masuk',
    'Logout' => 'Keluar',
    'Male' => 'Pria',
    'Name' => 'Nama',
    'Need an account? Sign up.' => 'Perlu akun? Daftar Sekarang.',
    'New password was saved.' => 'Password baru telah tersimpan.',
    'Page not found' => 'Halaman tidak ditemukan',
    'Password' => 'Password',
    'Password reset for {name}' => 'Password reset {name}',
    'Profile settings' => 'Pengaturan Profil',
    'Remember Me' => 'Ingat saya',
    'Request password reset' => 'Minta reset password',
    'Reset password' => 'Rerset password',
    'Settings' => 'Pengaturan',
    'Sign up with' => 'Masuk dengan',
    'Signup' => 'Daftar',
    'Sorry, we are unable to reset password for email provided.' => 'Maaf, gagal mereset password dengan email tersebut',
    'Subject' => 'Subjek',
    'Submit' => 'Kirim',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Terima kasih telah menghubungi, nantikan kami menghubungi anda kembali.',
    'There was an error sending email.' => 'Ada kerusakan saat mengirim surel.',
    'This email address has already been taken.' => 'Alamat Surel ini sudah pernah digunakan.',
    'This email has already been taken.' => 'Surel ini sudah pernah digunakan.',
    'This username has already been taken.' => 'Username sudah pernah digunakan.',
    'Update' => 'Perbaharui',
    'User Settings' => 'Pengaturan pengguna',
    'Username' => 'Username',
    'Username or email' => 'Username atau surel',
    'Verification Code' => 'Kode Verifikasi',
    'We already have a user with email {email}' => 'Kami sudah memiliki pengguna dengan surel {email}',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Selamat datang di {app-name}. Surel berisi informasi login seharusnya sudah dikirimkan ke surel anda.',
    'Your account has been successfully activated.' => 'Akun anda telah berhasil diaktifkan.',
    'Your account has been successfully created. Check your email for further instructions.' => 'Akun anda sudah dibuat. Cek surel untuk instruksi lebih lanjut.',
    'Your account has been successfully saved' => 'Akun anda telah disimpan',
    'Your activation link: {url}' => 'LInk aktivasi anda: {url}',
    '{app-name} | Your login information' => '{app-name} | Informasi login anda',
    'Create' => 'Buat',
    'Create Rule' => '',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Jika anda lupa password anda dapat meresetnya di <a href="{link}">sini</a>',
    'Resend activation email' => 'Kirim ulang surel aktivasi',
    'Resend your activation email <a href="{link}">here</a>' => 'Kirim ulang surel aktivasi di <a href="{link}">sini</a>',
    'Rules' => '',
    'Search' => '',
    'Sorry, we are unable to resend activation link for email provided.' => 'Maaf, kami tidak berhasil mengirim ulang link aktivasi ke surel tersebut',
];
