<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'O nas',
    'Account Settings' => 'Ustawienia konta',
    'Activation email' => 'Email aktywacyjny',
    'Articles' => 'Artykuły',
    'Attachments' => 'Załączniki',
    'Backend' => 'Backend',
    'Body' => 'Treść',
    'Check your email for further instructions.' => 'Sprawdź swoją skrzynkę pocztową',
    'Confirm Password' => 'Potwierdź hasło',
    'Contact' => 'Kontakt',
    'E-mail' => 'Adres E-mail',
    'Email' => 'Adres Email',
    'Error while oauth process.' => 'Błąd podczas przetwarzania autoryzacji OAuth',
    'Female' => 'Kobieta',
    'Home' => 'Strona główna',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Jeżeli zapomnisz swoje hasło możesz je zresetować <a href="{link}">tutaj</a>',
    'Incorrect username or password.' => 'Nieprawidłowa nazwa użytkownika lub hasło',
    'Language' => 'Język',
    'Log in with' => 'Zaloguj się przez',
    'Login' => 'Logowanie',
    'Logout' => 'Wyloguj',
    'Male' => 'Mężczyzna',
    'Name' => 'Nazwa',
    'Need an account? Sign up.' => 'Potrzebujesz konta? Zarejestruj się',
    'New password was saved.' => 'Nowe hasło zostało zapisane',
    'Page not found' => 'Strony nie znaleziono',
    'Password' => 'Hasło',
    'Password reset for {name}' => 'Resetowanie hasła dla {name}',
    'Profile settings' => 'Ustawienia profilu',
    'Remember Me' => 'Zapamiętaj mnie',
    'Request password reset' => 'Poproś o zresetowanie hasła',
    'Reset password' => 'Resetowanie hasła',
    'Settings' => 'Ustawienia',
    'Sign up with' => 'Zarejestruj się przez',
    'Signup' => 'Zarejestruj',
    'Sorry, we are unable to reset password for email provided.' => 'Przepraszamy, nie jesteśmy w stanie zresetować hasła dla podanego adres email',
    'Subject' => 'Tytuł',
    'Submit' => 'Wyślij',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Dziękujemy za kontakt z nami. Postaramy się odpisać najszybciej jak to będzie możliwe',
    'There was an error sending email.' => 'Pojawił się błąd przy wysyłaniu wiadomości',
    'This email address has already been taken.' => 'Ten adres email jest zajęty',
    'This email has already been taken.' => 'Ten adres email jest zajęty',
    'This username has already been taken.' => 'Ta nazwa użytkonika jest zajęta',
    'Update' => 'Aktualizuj',
    'User Settings' => 'Ustawienia użytkownika',
    'Username' => 'Nazwa użytkonika',
    'Username or email' => 'Nazwa użytkonika lub email',
    'Verification Code' => 'Kod weryfikacyjny',
    'We already have a user with email {email}' => 'Mamy już użytkownika o adresie email {email}',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Witaj w {app-name}. Wiadomość z danymi potrzebnymi do logowania zostały wysłane na twój adres email',
    'Your account has been successfully activated.' => 'Twoje konto zostało pomyślnie aktywowane',
    'Your account has been successfully created. Check your email for further instructions.' => 'Twoje konto zostało utworzone. Sprawdź swoją skrzynkę pocztową',
    'Your account has been successfully saved' => 'Twoje konto zostało pomyślnie zapisane',
    'Your activation link: {url}' => 'Twój link aktywacyjny {url}',
    '{app-name} | Your login information' => '{app-name} | Twoje dane logowania',
];
