<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активно',
    'Administrator' => 'Адміністратор',
    'Alias' => 'Псевдонім',
    'Body' => 'Текст',
    'Caption' => 'Текст',
    'Carousel ID' => 'ID каруселі',
    'Category' => 'Категорія',
    'Config' => 'Налаштування',
    'Created At' => 'Створено',
    'Deleted' => 'Видалено',
    'FileStorage: cannot generate file name' => 'FileStorage: не можу згенерувати ім’я файла',
    'Firstname' => 'Ім’я',
    'Gender' => 'Стать',
    'ID' => 'ID',
    'Key' => 'Ключ',
    'Lastname' => 'Прізвище',
    'Manager' => 'Менеджер',
    'Middlename' => 'По батькові',
    'Mime Type' => 'Mime тип',
    'Name cannot be empty' => 'Ім’я не може бути порожнім',
    'Order' => 'Порядок',
    'Path' => 'Шлях',
    'Picture' => 'Аватар',
    'Published At' => 'Опубліковано',
    'Repository' => 'Сховище',
    'Size' => 'Розмір',
    'Status' => 'Статус',
    'Title' => 'Назва',
    'Updated At' => 'Оновлено',
    'Upload IP Adress' => 'IP адреса',
    'Upload Time' => 'Час завантаження',
    'Url' => 'Url',
    'User' => 'Користувач',
    'User ID' => 'ID Користувача',
    'Value' => 'Значення',
    '{attribute} must be a valid JSON' => '{attribute} повинен бути валідним JSON',
];
