<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Are you sure ypu want to reset File Storage?' => '',
    'Article Categories' => '',
    'Articles' => '',
    'Carousel Widgets' => '',
    'Carousel slide was successfully saved' => '',
    'Category' => '',
    'Clear' => '',
    'Content' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Dashboard' => '',
    'Delete' => '',
    'File Manager' => '',
    'File Storage Items' => '',
    'Hello, {username}' => 'Здравствуйте, {username}',
    'ID' => '',
    'Key Storage Items' => '',
    'Key-Value Storage' => '',
    'Language' => '',
    'Level' => '',
    'Log Time' => '',
    'Logout' => '',
    'Logs' => '',
    'Member since {0, date, short}' => '',
    'Menu Widgets' => '',
    'Message' => '',
    'New user' => '',
    'New user {username} ({email}) war registered at {created_at, date} {created_at, time}' => '',
    'Pages' => '',
    'Prefix' => '',
    'Reset' => '',
    'Reset file storage' => '',
    'Search' => '',
    'Sign In' => '',
    'Sign me in' => '',
    'Static pages' => '',
    'System' => '',
    'System Events' => '',
    'System Logs' => '',
    'Text Blocks' => '',
    'Text Widgets' => '',
    'Toggle navigation' => '',
    'Translation' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Upload file' => '',
    'Used size' => '',
    'Users' => '',
    'View all' => '',
    'Widget Carousel' => '',
    'Widget Carousel Items' => '',
    'Widget Carousels' => '',
    'Widget Menus' => '',
    'You have {num} events' => '',
    'You have {num} log items' => '',
];
