<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Settings' => 'Thiết lập tài khoản',
    'Activation email' => 'Kích hoạt email',
    'Articles' => 'Danh sách bài viết',
    'Backend' => 'Ban quản trị',
    'Body' => 'Nội dung',
    'Check your email for further instructions.' => 'Kiểm tra email của bạn để biết thêm thông tin.',
    'Confirm Password' => 'Xác nhận mật khẩu',
    'Contact' => 'Liên hệ',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Có lỗi xảy ra trong quá trình xác thực.',
    'Female' => 'Nữ',
    'Home' => 'Trang chủ',
    'Incorrect username or password.' => 'Sai tên đăng nhập hoặc mật khẩu',
    'Language' => 'Ngôn ngữ',
    'Log in with' => 'Đăng nhập với',
    'Login' => 'Đăng nhập',
    'Logout' => 'Đăng xuất',
    'Male' => 'Nữ',
    'Name' => 'Tên',
    'Need an account? Sign up.' => 'Chưa có tài khoản? Đăng ký',
    'New password was saved.' => 'Mật khẩu mới đã được lưu',
    'Page not found' => 'Không tìm thấy trang',
    'Password' => 'Mật khẩu',
    'Password reset for {name}' => 'Cấp lại mật khẩu cho {name}',
    'Profile settings' => 'Thiết lập hồ sơ',
    'Remember Me' => 'Lưu thông tin đăng nhập',
    'Request password reset' => 'Yêu cầu thay đổi mật khẩu',
    'Reset password' => 'Cấp lại mật khẩu',
    'Settings' => 'Thiết lập',
    'Sign up with' => 'Đăng ký với',
    'Signup' => 'Đăng ký tài khoản',
    'Sorry, we are unable to reset password for email provided.' => 'Xin lỗi, chúng tôi không thể cấp lại mật khẩu cho email này.',
    'Subject' => 'Tiêu đề',
    'Submit' => 'Gửi lên',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Cảm ơn bạn đã gửi liên hệ, chúng tôi sẽ phản hồi trong thời gian sớm nhất.',
    'There was an error sending email.' => 'Có lỗi xảy ra khi gửi email',
    'This email address has already been taken.' => 'Địa chỉ email đã tồn tại',
    'This email has already been taken.' => 'Email này đã tồn tại',
    'This username has already been taken.' => 'Tên đăng nhập đã tồn tại',
    'Update' => 'Cập nhật',
    'User Settings' => 'Thiết lập thành viên',
    'Username' => 'Tên đăng nhập',
    'Username or email' => 'Tên đăng nhập hoặc email',
    'Verification Code' => 'Mã xác nhận',
    'We already have a user with email {email}' => 'Đia chỉ email {email} đã có người dùng',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Chào mừng bạn tới {app-name}. Thông tin đăng nhập đã được gửi tới địa chỉ email của bạn',
    'Your account has been successfully activated.' => 'Tài khoản của bạn được kích hoạt thành công',
    'Your account has been successfully created. Check your email for further instructions.' => 'Tài khoản đã được tạo thành công. Vui lòng kiểm tra email để biết thêm thông tin',
    'Your account has been successfully saved' => 'Lưu thông tin tài khoản thành công',
    'Your activation link: {url}' => 'Đường đẫn kích hoạt',
    '{app-name} | Your login information' => '{app-name} | Thông tin đăng nhập của bạn',
    'About' => '',
    'Archive' => '',
    'Categories' => '',
    'Categories not found' => '',
    'Change Password' => '',
    'Contact Support' => '',
    'Contact us' => '',
    'Create Rule' => '',
    'Forgot your password?' => '',
    'Go to Home' => '',
    'Last updated on {updated_at} by {updater}' => '',
    'No records' => '',
    'Oops! There was an error...' => '',
    'Posted by {author} on {published_at}' => '',
    'Read More ' => '',
    'Resend activation email' => '',
    'Resend my activation email' => '',
    'Rules' => '',
    'Send Email' => '',
    'Sign up' => '',
    'Sorry, we are unable to resend activation link for email provided.' => '',
    'by {author} on {published_at} in {category}' => '',
];
