<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Last login' => 'Останній захід',
    'Updated at' => 'Останне оновлення',
    '"{attribute}" must be a valid JSON' => '"{attribute}" повинен містити валідний JSON',
    'Active' => 'Активно',
    'Administrator' => 'Адміністратор',
    'Article ID' => 'ID Статті',
    'Author' => 'Автор',
    'Base Url' => 'Базовий Url',
    'Body' => 'Текст',
    'Caption' => 'Текст',
    'Carousel ID' => 'ID каруселі',
    'Category' => 'Категорія',
    'Comment' => 'Коментар',
    'Component' => 'Компонент',
    'Config' => 'Налаштування',
    'Created At' => 'Створено',
    'Created at' => 'Створено',
    'Deleted' => 'Видалено',
    'Down to maintenance.' => 'Закрито на обслуговування.',
    'E-mail' => 'E-mail',
    'Firstname' => 'Ім’я',
    'Gender' => 'Стать',
    'ID' => 'ID',
    'Key' => 'Ключ',
    'Lastname' => 'Прізвище',
    'Locale' => 'Локаль',
    'Manager' => 'Менеджер',
    'Middlename' => 'По батькові',
    'Name' => 'Им\'я',
    'Order' => 'Порядок',
    'Parent Category' => 'Батьківська категорія',
    'Path' => 'Шлях',
    'Picture' => 'Аватар',
    'Published' => 'Опубліковано',
    'Published At' => 'Опубліковано',
    'Role' => 'Роль',
    'Size' => 'Розмір',
    'Slug' => 'ЧПУ',
    'Status' => 'Статус',
    'Title' => 'Назва',
    'Type' => 'Тип',
    'Updated At' => 'Оновлено',
    'Updater' => 'Оновлено',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User' => 'Користувач',
    'User ID' => 'ID Користувача',
    'Username' => 'Им’я користувача',
    'Value' => 'Значення',
];
