<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{attribute}" must be a valid JSON' => '"{attribute}" повинен містити валідний JSON',
    'Active' => 'Активно',
    'Article ID' => 'ID Статті',
    'Article View' => 'Шаблон статті',
    'Author' => 'Автор',
    'Base URL' => 'Базовий URL',
    'Base Url' => 'Базовий Url',
    'Body' => 'Текст',
    'Caption' => 'Текст',
    'Carousel ID' => 'ID каруселі',
    'Category' => 'Категорія',
    'Comment' => 'Коментар',
    'Component' => 'Компонент',
    'Config' => 'Налаштування',
    'Created At' => 'Створено',
    'Created at' => 'Створено',
    'Deleted' => 'Видалено',
    'Down to maintenance.' => 'Закрито на обслуговування.',
    'E-mail' => 'E-mail',
    'File Type' => 'Тип файлу',
    'Firstname' => 'Ім’я',
    'Gender' => 'Стать',
    'ID' => 'ID',
    'Image' => 'Зображення',
    'Key' => 'Ключ',
    'Last login' => 'Останній вхід',
    'Lastname' => 'Прізвище',
    'Locale' => 'Локаль',
    'Middlename' => 'По батькові',
    'Name' => 'Им\'я',
    'Order' => 'Порядок',
    'Page View' => 'Шаблон сторінки',
    'Parent Category' => 'Батьківська категорія',
    'Path' => 'Шлях',
    'Picture' => 'Аватар',
    'Published' => 'Опубліковано',
    'Published At' => 'Опубліковано',
    'Size' => 'Розмір',
    'Slug' => 'ЧПУ',
    'Status' => 'Статус',
    'Thumbnail' => 'Ескіз',
    'Title' => 'Назва',
    'Type' => 'Тип',
    'Updated At' => 'Оновлено',
    'Updated at' => 'Останне оновлення',
    'Updater' => 'Оновлено',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'ID Користувача',
    'Username' => 'Им’я користувача',
    'Value' => 'Значення',
    'API access token' => '',
    'Draft' => '',
    'Email' => '',
    'Expire At' => '',
    'Not Active' => '',
    'Password' => '',
    'Roles' => '',
    'Token' => '',
];
