<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirm Password' => 'Підтвердження пароля',
    'E-mail' => 'E-mail',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Якщо ви забули свій пароль, ви можете скинуту його <a href="{link}">тут</a>',
    'Need an account? Sign up.' => 'Потрібен аккаунт? Зареєструйтесь',
    'Remember Me' => 'Запом’ятати мене',
    'Request password reset' => 'Запит на скидання пароля',
    'Reset password' => 'Скидання пароля',
    'About' => 'О нас',
    'Account' => 'Аккаунт',
    'Articles' => 'Статті',
    'Backend' => 'Панель управління',
    'Check your email for further instructions.' => 'Перевірте ваш e-mail.',
    'Contact' => 'Контакти',
    'Create' => 'Створити',
    'Error while oauth process.' => 'Помилка під час OAuth авторизації.',
    'Female' => 'Жіноча',
    'Home' => 'Головна',
    'Incorrect username or password.' => 'Неправильні им’я користувача або пароль',
    'Language' => 'Мова',
    'Log in with' => 'Увійти за допомогою',
    'Login' => 'Вхід',
    'Logout' => 'Вихід',
    'Male' => 'Чоловіча',
    'New password was saved.' => 'Новий пароль було збережено',
    'Page not found' => 'Сторінка не знайдена',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Скидання пароля для {name}',
    'Profile' => 'Профіль',
    'Sign up with' => 'Створити аккаунт за допомогою',
    'Signup' => 'Реєстрація',
    'Sorry, we are unable to reset password for email provided.' => 'Вибачте, але ми не можемо скинути пароль для цього e-mail.',
    'This email address has already been taken.' => 'Цей e-mail вже зайнятий',
    'This username has already been taken.' => 'Це им\'я користувача вже використовується',
    'Update' => 'Зберегти',
    'Username' => 'Им\'я користувача',
    'Username or email' => 'Им’я користувача або e-mail',
    'We already have a user with email {email}' => 'Користувач с e-mail {email} вже зареэстрований',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Вітаємо у {app-name}. Вам був надісланий e-mail с інформациєю щодо користувача',
    'Your profile has been successfully saved' => 'Ваш профіль було успішно збережено',
    '{app-name} | Your login information' => '{app-name} | Інформація про користувача',
];
