<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'О нас',
    'Account Settings' => 'Налаштування аккаунта',
    'Articles' => 'Статті',
    'Backend' => 'Панель управління',
    'Body' => 'Повідомлення',
    'Check your email for further instructions.' => 'Перевірте ваш e-mail.',
    'Confirm Password' => 'Підтвердження пароля',
    'Contact' => 'Контакти',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Помилка під час OAuth авторизації.',
    'Female' => 'Жіноча',
    'Home' => 'Головна',
    'Incorrect username or password.' => 'Неправильні им’я користувача або пароль',
    'Language' => 'Мова',
    'Log in with' => 'Увійти за допомогою',
    'Login' => 'Вхід',
    'Logout' => 'Вихід',
    'Male' => 'Чоловіча',
    'Name' => 'Ім’я',
    'Need an account? Sign up.' => 'Потрібен аккаунт? Зареєструйтесь',
    'New password was saved.' => 'Новий пароль було збережено',
    'Page not found' => 'Сторінка не знайдена',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Скидання пароля для {name}',
    'Profile settings' => 'Налаштування профілю',
    'Remember Me' => 'Запом’ятати мене',
    'Request password reset' => 'Запит на скидання пароля',
    'Reset password' => 'Скидання пароля',
    'Settings' => 'Налаштування',
    'Sign up with' => 'Створити аккаунт за допомогою',
    'Signup' => 'Реєстрація',
    'Sorry, we are unable to reset password for email provided.' => 'Вибачте, але ми не можемо скинути пароль для цього e-mail.',
    'Subject' => 'Тема',
    'Submit' => 'Відправити',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Дякуэмо. Ми відповімо Вам якнайшвидше.',
    'There was an error sending email.' => 'Сталася помилка при відправці email',
    'This email address has already been taken.' => 'Цей e-mail вже зайнятий',
    'This username has already been taken.' => 'Це им\'я користувача вже використовується',
    'Update' => 'Зберегти',
    'User Settings' => 'Налаштування користувача',
    'Username' => 'Им\'я користувача',
    'Username or email' => 'Им’я користувача або e-mail',
    'Verification Code' => 'Код перевірки',
    'We already have a user with email {email}' => 'Користувач с e-mail {email} вже зареэстрований',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Вітаємо у {app-name}. Вам був надісланий e-mail с інформациєю щодо користувача',
    'Your account has been successfully saved' => 'Ваш аккаунт було успішно збережено',
    '{app-name} | Your login information' => '{app-name} | Інформація про користувача',
    'Activation email' => '',
    'Archive' => '',
    'Categories' => '',
    'Categories not found' => '',
    'Change Password' => '',
    'Contact Support' => '',
    'Contact us' => '',
    'Create Rule' => '',
    'Forgot your password?' => '',
    'Go to Home' => '',
    'Last updated on {updated_at} by {updater}' => '',
    'No records' => '',
    'Oops! There was an error...' => '',
    'Posted by {author} on {published_at}' => '',
    'Read More ' => '',
    'Resend activation email' => '',
    'Resend my activation email' => '',
    'Rules' => '',
    'Send Email' => '',
    'Sign up' => '',
    'Sorry, we are unable to resend activation link for email provided.' => '',
    'This email has already been taken.' => '',
    'Your account has been successfully activated.' => '',
    'Your account has been successfully created. Check your email for further instructions.' => '',
    'Your activation link: {url}' => '',
    'by {author} on {published_at} in {category}' => '',
];
