<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error while oauth process' => 'Помилка у процессі oauth авторизації',
    'Log in with' => 'Увійти за допомогою',
    'Sign up with' => 'Створити аккаунт за допомогою',
    'Username' => 'Им\'я користувача',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '',
    '{app-name} | Your login information' => '',
    'About' => 'О нас',
    'Account' => 'Аккаунт',
    'Articles' => 'Статті',
    'Backend' => 'Панель управління',
    'Contact' => 'Контакти',
    'Create' => 'Створити',
    'Female' => 'Жіноча',
    'Home' => 'Головна',
    'Language' => 'Мова',
    'Login' => 'Вхід',
    'Logout' => 'Вихід',
    'Male' => 'Чоловіча',
    'Page not found' => 'Сторінка не знайдена',
    'Password' => 'Пароль',
    'Profile' => 'Профіль',
    'Signup' => 'Реєстрація',
    'This username has already been taken.' => 'Це им\'я користувача вже використовується',
    'Update' => 'Зберегти',
    'Username or password' => 'Ім’я користувача або пароль',
    'Your profile has been successfully saved' => 'Ваш профіль було успішно збережено',
];
