<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Article View' => '',
    'Page View' => '',
    '"{attribute}" must be a valid JSON' => '"{attribute}" debe de ser un JSON válido',
    'Active' => 'Activo',
    'Article ID' => 'ID Artículo',
    'Author' => 'Autor',
    'Base URL' => 'URL Base',
    'Base Url' => 'Url Base',
    'Body' => 'Cuerpo',
    'Caption' => 'Leyenda',
    'Carousel ID' => 'Carrusel ID',
    'Category' => 'Categoría',
    'Comment' => 'Comentario',
    'Component' => 'Componente',
    'Config' => 'Configuración',
    'Created At' => 'Creado el',
    'Created at' => 'Creado el',
    'Deleted' => 'Borrado',
    'Down to maintenance.' => 'Apagado por mantenimiento.',
    'E-mail' => 'E-mail',
    'File Type' => 'Tipo fichero',
    'Firstname' => 'Nombre',
    'Gender' => 'Género',
    'ID' => 'ID',
    'Image' => 'Imagen',
    'Key' => 'Clave',
    'Last login' => 'ültimo Login',
    'Lastname' => 'Apellido',
    'Locale' => 'Pais',
    'Middlename' => 'Middlename',
    'Name' => 'Nombre',
    'Order' => 'Orden',
    'Parent Category' => 'Categoría Parental',
    'Path' => 'Camino',
    'Picture' => 'Imagen',
    'Published' => 'Publicado',
    'Published At' => 'Publicado el',
    'Size' => 'Tamaño',
    'Slug' => 'Slug',
    'Status' => 'Estado',
    'Thumbnail' => 'Miniatura',
    'Title' => 'Tñitulo',
    'Type' => 'Tipo',
    'Updated At' => 'Actualizado el',
    'Updated at' => 'Actualizado ',
    'Updater' => 'Actualizador',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'Usuario ID',
    'Username' => 'Nombre Usuario',
    'Value' => 'Valor',
];
