<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Settings' => 'Configuración de la cuenta',
    'Profile settings' => 'Configuración del perfil',
    'Settings' => 'Configuración',
    'User Settings' => 'Configuración de usuario',
    'About' => 'Sobre',
    'Articles' => 'Artículos',
    'Attachments' => 'Adjuntos',
    'Backend' => 'Segundo Plano',
    'Body' => 'Cuerpo',
    'Check your email for further instructions.' => 'Comprueba  tu email para más instrucciones.',
    'Confirm Password' => 'Confirmar palabra de paso',
    'Contact' => 'Contacto',
    'E-mail' => 'Email',
    'Email' => 'Email',
    'Error while oauth process.' => 'Error en el proceso de OAuth.',
    'Female' => 'Mujer',
    'Home' => 'Hombre',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Si has olvidado la Palabra de paso puedes cambiarla <a href="{link}">aquí</a>',
    'Incorrect username or password.' => 'Nombre de usuario o palabra de paso incorrectos',
    'Language' => 'Idioma',
    'Log in with' => 'Conectado como',
    'Login' => 'Conectar',
    'Logout' => 'Desconectar',
    'Male' => 'Hombre',
    'Name' => 'Nombre',
    'Need an account? Sign up.' => '¿Necesitas una cuenta?, re´gístrate',
    'New password was saved.' => 'La nueva palabra de paso ha sido guardada',
    'Page not found' => 'Página no encontrada',
    'Password' => 'Palabra de paso',
    'Password reset for {name}' => 'Palabra de paso cambiada para {name}',
    'Remember Me' => 'Recuérdame',
    'Request password reset' => 'Solicita cambiar la palabra de paso',
    'Reset password' => 'Cambiar Palabra de Paso',
    'Sign up with' => 'Registrado con',
    'Signup' => 'Registrado',
    'Sorry, we are unable to reset password for email provided.' => 'Lo siento, no puedo cambiar el password para el email provisto.',
    'Subject' => 'Tema',
    'Submit' => 'Enviar',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Gracias por contactarnos. responderemos tan pronto como sea posible.',
    'There was an error sending email.' => 'Ha ocurrido un error enviando el correo',
    'This email address has already been taken.' => 'La dirección de correo ya ha sido usada',
    'This username has already been taken.' => 'El nombre de usuario ya ha sido usado',
    'Update' => 'Actualiza',
    'Username' => 'Nombre de usuario',
    'Username or email' => 'Nombre de usuario o email',
    'Verification Code' => 'Código de verificación',
    'We already have a user with email {email}' => 'Ya tenemos un usuario con el correo {email} ',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '¡Bienvenido a {app-name}!. Un correo con la información de su conexión ha sido enviado a su correo',
    'Your account has been successfully saved' => 'Su cuenta ha sido grabada con éxito',
    '{app-name} | Your login information' => '{app-name} | Información de conexión',
];
