<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Acerca de',
    'Account Settings' => 'Configuración de la cuenta',
    'Activation email' => 'Email de activación',
    'Archive' => 'Archivo',
    'Articles' => 'Artículos',
    'Backend' => 'Backend',
    'Body' => 'Contenido',
    'Categories' => 'Categorías',
    'Categories not found' => 'Sin categoriías',
    'Change Password' => 'Cambiar Contraseña',
    'Check your email for further instructions.' => 'Verifica tu correo para más instrucciones.',
    'Confirm Password' => 'Confirmar contraseña',
    'Contact' => 'Contacto',
    'Contact us' => 'Contáctanos',
    'Create Rule' => 'Añadir Regla',
    'E-mail' => 'Email',
    'Email' => 'Email',
    'Error while oauth process.' => 'Error en el proceso de OAuth.',
    'Female' => 'Mujer',
    'Forgot your password?' => 'Olvidaste tu contraseña?',
    'Home' => 'Inicio',
    'Incorrect username or password.' => 'Nombre de usuario o contraseña incorrectos',
    'Language' => 'Idioma',
    'Last updated on {updated_at} by {updater}' => 'Modificado el {updated_at} por {updater}',
    'Log in with' => 'Ingresar con',
    'Login' => 'Ingresar',
    'Logout' => 'Salir',
    'Male' => 'Hombre',
    'Name' => 'Nombre',
    'Need an account? Sign up.' => '¿Necesitas una cuenta?. Regístrate.',
    'New password was saved.' => 'La nueva contraseña ha sido guardada',
    'No records' => 'Sin registros',
    'Page not found' => 'Página no encontrada',
    'Password' => 'Contraseña',
    'Password reset for {name}' => 'Cambio de contraseña para {name}',
    'Posted by {author} on {published_at}' => 'Publicado por {author} el {published_at}',
    'Profile settings' => 'Ajustes de perfil',
    'Read More ' => 'Seguir Leyendo',
    'Remember Me' => 'Recordar mis datos',
    'Request password reset' => 'Solicita cambio de contraseña',
    'Resend activation email' => 'Reenviar activación por email',
    'Resend my activation email' => 'Reenviar mi email de activación',
    'Reset password' => 'Cambiar Contraseña',
    'Rules' => 'Reglas',
    'Send Email' => 'Enviar email',
    'Settings' => 'Ajustes',
    'Sign up' => 'Registrarse',
    'Sign up with' => 'Regístrate con',
    'Signup' => 'Regístrate',
    'Sorry, we are unable to resend activation link for email provided.' => 'Lo sentimos, no se pudo reenviar el correo de activación al email provisto',
    'Sorry, we are unable to reset password for email provided.' => 'Lo sentimos, no se puede cambiar la contraseña para el email provisto.',
    'Subject' => 'Asunto',
    'Submit' => 'Enviar',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Gracias por contactarnos. responderemos tan pronto como sea posible.',
    'There was an error sending email.' => 'Ha ocurrido un error al enviar el correo',
    'This email address has already been taken.' => 'La dirección de correo ya ha sido usada',
    'This email has already been taken.' => 'Este correo ya está siendo utilizado',
    'This username has already been taken.' => 'El nombre de usuario ya está siendo usado',
    'Update' => 'Actualizar',
    'User Settings' => 'Ajustes de usuario',
    'Username' => 'Nombre de usuario',
    'Username or email' => 'Nombre de usuario o email',
    'Verification Code' => 'Código de verificación',
    'We already have a user with email {email}' => 'Ya tenemos un usuario con el correo {email} ',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '¡Bienvenido a {app-name}!. Un correo con la información de su conexión ha sido enviado a su correo',
    'Your account has been successfully activated.' => 'Tu cuenta ha sido activada correctamente.',
    'Your account has been successfully created. Check your email for further instructions.' => 'Tu cuenta ha sido creada correctamente. Revisa tu correo para seguir con las instrucciones.',
    'Your account has been successfully saved' => 'Su cuenta ha sido guardada con éxito',
    'Your activation link: {url}' => 'Tu link de activación: {url}',
    'by {author} on {published_at} in {category}' => 'por {author} el {published_at} in {category}',
    '{app-name} | Your login information' => '{app-name} | Información de conexión',
    'Contact Support' => 'Contactar a Soporte',
    'Go to Home' => 'Ir al Inicio',
    'Oops! There was an error...' => 'Ups! Hubo un error...',
];
