<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation email' => 'Correo de activación',
    'This email has already been taken.' => 'Este correo está siendo utilizado',
    'Your account has been successfully activated.' => 'Tu cuenta ha sido activada correctamente.',
    'Your account has been successfully created. Check your email for further instructions.' => 'Tu cuenta ha sido creada correctamente. Revisa tu correo para más instrucciones.',
    'Your activation link: {url}' => 'Tu link de activación: {url}',
    'About' => 'Acerca de',
    'Account Settings' => 'Configuración de la cuenta',
    'Articles' => 'Artículos',
    'Attachments' => 'Adjuntos',
    'Backend' => 'Backend',
    'Body' => 'Cuerpo',
    'Check your email for further instructions.' => 'Verifica tu correo para más instrucciones.',
    'Confirm Password' => 'Confirmar contraseña',
    'Contact' => 'Contacto',
    'E-mail' => 'Email',
    'Email' => 'Email',
    'Error while oauth process.' => 'Error en el proceso de OAuth.',
    'Female' => 'Mujer',
    'Home' => 'Inicio',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Si has olvidado tu contraseña puedes cambiarla <a href="{link}">aquí</a>',
    'Incorrect username or password.' => 'Nombre de usuario o contraseña incorrectos',
    'Language' => 'Idioma',
    'Log in with' => 'Conectado como',
    'Login' => 'Conectar',
    'Logout' => 'Desconectar',
    'Male' => 'Hombre',
    'Name' => 'Nombre',
    'Need an account? Sign up.' => '¿Necesitas una cuenta?, regístrate',
    'New password was saved.' => 'La nueva contraseña ha sido guardada',
    'Page not found' => 'Página no encontrada',
    'Password' => 'Contraseña',
    'Password reset for {name}' => 'Contraseña cambiada para {name}',
    'Profile settings' => 'Configuración del perfil',
    'Remember Me' => 'Recuérdame',
    'Request password reset' => 'Solicita cambio de la contraseña',
    'Reset password' => 'Cambiar Contraseña',
    'Settings' => 'Configuración',
    'Sign up with' => 'Regístrate con',
    'Signup' => 'Regístrate',
    'Sorry, we are unable to reset password for email provided.' => 'Lo siento, no se puede cambiar la contraseña para el email provisto.',
    'Subject' => 'Tema',
    'Submit' => 'Enviar',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Gracias por contactarnos. responderemos tan pronto como sea posible.',
    'There was an error sending email.' => 'Ha ocurrido un error al enviar el correo',
    'This email address has already been taken.' => 'La dirección de correo ya ha sido usada',
    'This username has already been taken.' => 'El nombre de usuario ya está siendo usado',
    'Update' => 'Actualizar',
    'User Settings' => 'Configuración de usuario',
    'Username' => 'Nombre de usuario',
    'Username or email' => 'Nombre de usuario o email',
    'Verification Code' => 'Código de verificación',
    'We already have a user with email {email}' => 'Ya tenemos un usuario con el correo {email} ',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '¡Bienvenido a {app-name}!. Un correo con la información de su conexión ha sido enviado a su correo',
    'Your account has been successfully saved' => 'Su cuenta ha sido guardada con éxito',
    '{app-name} | Your login information' => '{app-name} | Información de conexión',
];
