<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активно',
    'Administrator' => 'Администратор',
    'Alias' => 'Псевдоним',
    'Body' => 'Текст',
    'Caption' => 'Текст',
    'Carousel ID' => 'ID карусели',
    'Category' => 'Категория',
    'Config' => 'Настройки',
    'Created At' => 'Создано',
    'Deleted' => 'Удалено',
    'FileStorage: cannot generate file name' => 'FileStorage: не могу сгенерировать имя файла',
    'Firstname' => 'Имя',
    'Gender' => 'Пол',
    'ID' => 'ID',
    'Key' => 'Ключ',
    'Lastname' => 'Фамилия',
    'Manager' => 'Менеджер',
    'Middlename' => 'Отчество',
    'Mime Type' => 'Mime тип',
    'Name cannot be empty' => 'Имя не может быть пустым',
    'Order' => 'Порядок',
    'Path' => 'Путь',
    'Picture' => 'Аватар',
    'Published At' => 'Опубликовано',
    'Repository' => 'Хранилище',
    'Size' => 'Размер',
    'Status' => 'Статус',
    'Title' => 'Название',
    'Updated At' => 'Обновлено',
    'Upload IP Adress' => 'IP адрес',
    'Upload Time' => 'Время загрузки',
    'Url' => 'Url',
    'User' => 'Пользователь',
    'User ID' => 'ID пользователя',
    'Value' => 'Значние',
    '{attribute} must be a valid JSON' => '{attribute} должен быть валидным JSON',
];
