<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error while oauth process' => 'Ошибка при обработке oauth авторизации',
    'Log in with' => 'Войти с помощью',
    'Password' => 'Пароль',
    'Sign up with' => 'Создать аккаунт с помощью',
    'Username' => 'Имя пользователя',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '',
    '{app-name} | Your login information' => '',
    'About' => 'О нас',
    'Account' => 'Аккаунт',
    'Articles' => 'Статьи',
    'Backend' => 'Панель управления',
    'Contact' => 'Контакты',
    'Create' => 'Создать',
    'Female' => 'Женский',
    'Home' => 'Главная',
    'Language' => 'Язык',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Male' => 'Мужской',
    'Page not found' => 'Страница не найдена',
    'Profile' => 'Профиль',
    'Signup' => 'Регистрация',
    'This username has already been taken.' => 'Это имя пользователя уже занято',
    'Update' => 'Редактировать',
    'Username or password' => 'Имя пользователя или пароль',
    'Your profile has been successfully saved' => 'Ваш профиль бы успешно сохранен',
];
