<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirm Password' => 'Подтвердите пароль',
    'E-mail' => 'E-mail',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Если вы забыли пароль, вы можете сбросить его <a href="{link}">здесь</a>',
    'Need an account? Sign up.' => 'Нужен аккаунт? Зарегистрируйтесь',
    'Remember Me' => 'Запомнить меня',
    'Request password reset' => 'Запрос сброса пароля',
    'Reset password' => 'Сброс пароля',
    'About' => 'О нас',
    'Account' => 'Аккаунт',
    'Articles' => 'Статьи',
    'Backend' => 'Панель управления',
    'Check your email for further instructions.' => 'Проверьте ваш e-mail.',
    'Contact' => 'Контакты',
    'Create' => 'Создать',
    'Error while oauth process.' => 'Ошибка в процессе OAuth авторизации.',
    'Female' => 'Женский',
    'Home' => 'Главная',
    'Incorrect username or password.' => 'Неправильный логин или пароль.',
    'Language' => 'Язык',
    'Log in with' => 'Войти с помощью',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Male' => 'Мужской',
    'New password was saved.' => 'Новый пароль был сохранен',
    'Page not found' => 'Страница не найдена',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Сброс пароля для {name}',
    'Profile' => 'Профиль',
    'Sign up with' => 'Создать аккаунт с помощью',
    'Signup' => 'Регистрация',
    'Sorry, we are unable to reset password for email provided.' => 'Извините, мы не можем сбросить пароль для этого e-mail.',
    'This email address has already been taken.' => 'Этот e-mail уже занят',
    'This username has already been taken.' => 'Это имя пользователя уже занято',
    'Update' => 'Редактировать',
    'Username' => 'Имя пользователя',
    'Username or email' => 'Имя пользователя или e-mail',
    'We already have a user with email {email}' => 'Пользователь с email {email} уже зарегистрирован.',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Добро пожаловать в {app-name}. E-mail с информацией о пользователе был отправлен на вашу почту.',
    'Your profile has been successfully saved' => 'Ваш профиль бы успешно сохранен',
    '{app-name} | Your login information' => '{app-name} | Информация о пользователе',
];
